# Generated by Django 3.0.6 on 2020-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='Title1', max_length=150),
            preserve_default=False,
        ),
    ]
