# Generated by Django 3.0.6 on 2020-05-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200518_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-05-19'),
        ),
    ]
