# Generated by Django 3.0.6 on 2020-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200519_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='label_values',
        ),
        migrations.DeleteModel(
            name='status_values',
        ),
        migrations.AddField(
            model_name='todolist',
            name='label',
            field=models.CharField(default='Others', max_length=10),
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='New', max_length=10),
        ),
    ]
