# Generated by Django 3.0.6 on 2020-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200519_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-05-23'),
        ),
    ]
